// Generated by gencpp from file depthest/Point2DAged.msg
// DO NOT EDIT!


#ifndef DEPTHEST_MESSAGE_POINT2DAGED_H
#define DEPTHEST_MESSAGE_POINT2DAGED_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace depthest
{
template <class ContainerAllocator>
struct Point2DAged_
{
  typedef Point2DAged_<ContainerAllocator> Type;

  Point2DAged_()
    : x(0.0)
    , y(0.0)
    , age(0)
    , id(0)  {
    }
  Point2DAged_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , age(0)
    , id(0)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef int32_t _age_type;
  _age_type age;

   typedef int32_t _id_type;
  _id_type id;




  typedef boost::shared_ptr< ::depthest::Point2DAged_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::depthest::Point2DAged_<ContainerAllocator> const> ConstPtr;

}; // struct Point2DAged_

typedef ::depthest::Point2DAged_<std::allocator<void> > Point2DAged;

typedef boost::shared_ptr< ::depthest::Point2DAged > Point2DAgedPtr;
typedef boost::shared_ptr< ::depthest::Point2DAged const> Point2DAgedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::depthest::Point2DAged_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::depthest::Point2DAged_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace depthest

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'depthest': ['/home/peetaa/catkin_ws/src/depthest/msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'visualization_msgs': ['/opt/ros/kinetic/share/visualization_msgs/cmake/../msg'], 'tf2_msgs': ['/opt/ros/kinetic/share/tf2_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::depthest::Point2DAged_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::depthest::Point2DAged_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::depthest::Point2DAged_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::depthest::Point2DAged_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::depthest::Point2DAged_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::depthest::Point2DAged_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::depthest::Point2DAged_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d55844175301668ac8e67ab975076afe";
  }

  static const char* value(const ::depthest::Point2DAged_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd55844175301668aULL;
  static const uint64_t static_value2 = 0xc8e67ab975076afeULL;
};

template<class ContainerAllocator>
struct DataType< ::depthest::Point2DAged_<ContainerAllocator> >
{
  static const char* value()
  {
    return "depthest/Point2DAged";
  }

  static const char* value(const ::depthest::Point2DAged_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::depthest::Point2DAged_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 x\n\
float64 y\n\
int32 age\n\
int32 id\n\
";
  }

  static const char* value(const ::depthest::Point2DAged_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::depthest::Point2DAged_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.age);
      stream.next(m.id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Point2DAged_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::depthest::Point2DAged_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::depthest::Point2DAged_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "age: ";
    Printer<int32_t>::stream(s, indent + "  ", v.age);
    s << indent << "id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DEPTHEST_MESSAGE_POINT2DAGED_H
