// Generated by gencpp from file depthest/PoseAndPointsStamped.msg
// DO NOT EDIT!


#ifndef DEPTHEST_MESSAGE_POSEANDPOINTSSTAMPED_H
#define DEPTHEST_MESSAGE_POSEANDPOINTSSTAMPED_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <depthest/Point2D.h>
#include <depthest/Point2D.h>
#include <geometry_msgs/Point.h>
#include <geometry_msgs/Pose.h>

namespace depthest
{
template <class ContainerAllocator>
struct PoseAndPointsStamped_
{
  typedef PoseAndPointsStamped_<ContainerAllocator> Type;

  PoseAndPointsStamped_()
    : header()
    , points()
    , reprojectedPoints()
    , points3D()
    , pose()  {
    }
  PoseAndPointsStamped_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , points(_alloc)
    , reprojectedPoints(_alloc)
    , points3D(_alloc)
    , pose(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::depthest::Point2D_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::depthest::Point2D_<ContainerAllocator> >::other >  _points_type;
  _points_type points;

   typedef std::vector< ::depthest::Point2D_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::depthest::Point2D_<ContainerAllocator> >::other >  _reprojectedPoints_type;
  _reprojectedPoints_type reprojectedPoints;

   typedef std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Point_<ContainerAllocator> >::other >  _points3D_type;
  _points3D_type points3D;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _pose_type;
  _pose_type pose;




  typedef boost::shared_ptr< ::depthest::PoseAndPointsStamped_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::depthest::PoseAndPointsStamped_<ContainerAllocator> const> ConstPtr;

}; // struct PoseAndPointsStamped_

typedef ::depthest::PoseAndPointsStamped_<std::allocator<void> > PoseAndPointsStamped;

typedef boost::shared_ptr< ::depthest::PoseAndPointsStamped > PoseAndPointsStampedPtr;
typedef boost::shared_ptr< ::depthest::PoseAndPointsStamped const> PoseAndPointsStampedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::depthest::PoseAndPointsStamped_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::depthest::PoseAndPointsStamped_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace depthest

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'depthest': ['/home/peetaa/catkin_ws/src/depthest/msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'visualization_msgs': ['/opt/ros/kinetic/share/visualization_msgs/cmake/../msg'], 'tf2_msgs': ['/opt/ros/kinetic/share/tf2_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::depthest::PoseAndPointsStamped_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::depthest::PoseAndPointsStamped_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::depthest::PoseAndPointsStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::depthest::PoseAndPointsStamped_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::depthest::PoseAndPointsStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::depthest::PoseAndPointsStamped_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::depthest::PoseAndPointsStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9724887d78b797a5058a0a72b16e4007";
  }

  static const char* value(const ::depthest::PoseAndPointsStamped_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9724887d78b797a5ULL;
  static const uint64_t static_value2 = 0x058a0a72b16e4007ULL;
};

template<class ContainerAllocator>
struct DataType< ::depthest::PoseAndPointsStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "depthest/PoseAndPointsStamped";
  }

  static const char* value(const ::depthest::PoseAndPointsStamped_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::depthest::PoseAndPointsStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
Point2D[] points\n\
Point2D[] reprojectedPoints\n\
geometry_msgs/Point[] points3D\n\
geometry_msgs/Pose pose\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: depthest/Point2D\n\
float64 x\n\
float64 y\n\
\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of position and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::depthest::PoseAndPointsStamped_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::depthest::PoseAndPointsStamped_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.points);
      stream.next(m.reprojectedPoints);
      stream.next(m.points3D);
      stream.next(m.pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PoseAndPointsStamped_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::depthest::PoseAndPointsStamped_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::depthest::PoseAndPointsStamped_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "points[]" << std::endl;
    for (size_t i = 0; i < v.points.size(); ++i)
    {
      s << indent << "  points[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::depthest::Point2D_<ContainerAllocator> >::stream(s, indent + "    ", v.points[i]);
    }
    s << indent << "reprojectedPoints[]" << std::endl;
    for (size_t i = 0; i < v.reprojectedPoints.size(); ++i)
    {
      s << indent << "  reprojectedPoints[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::depthest::Point2D_<ContainerAllocator> >::stream(s, indent + "    ", v.reprojectedPoints[i]);
    }
    s << indent << "points3D[]" << std::endl;
    for (size_t i = 0; i < v.points3D.size(); ++i)
    {
      s << indent << "  points3D[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "    ", v.points3D[i]);
    }
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DEPTHEST_MESSAGE_POSEANDPOINTSSTAMPED_H
